"use client";

import { motion } from "framer-motion";
import { BadgeCheck, Camera, Compass, Download, Footprints, MapPin, ScrollText, Sparkles, TentTree } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { getPersona } from "@/data/catalog";
import { createResultHash, decodeSharedResult, encodeSharedResult } from "@/lib/share";
import type { Persona, Scores } from "@/lib/types";

type Stage = "world" | "order" | "map" | "checkin";
type Result = { persona: Persona; scores: Scores; answerPath: string; resultHash: string };
type Stop = { id: string; name: string; companion: string; image: string; time: string; route: string; activity: string; stamp: string; x: string; y: string };
const basePath = process.env.NEXT_PUBLIC_BASE_PATH ?? "";
const pathFor = (path: string) => `${basePath}${path}`;

const passes = [
  { kind: "夏尔步行证", service: "West Road · 西境古道", from: "霍比屯袋底洞", to: "瑞文戴尔幽谷", depart: "07:10", arrive: "次日 16:30", duration: "2 天", seat: "远征队第 06 位 · 徒步席", note: "带足第二顿早餐，越过布理后跟随星光与河谷前进。" },
  { kind: "精灵渡河证", service: "Anduin Passage · 安都因河线", from: "瑞文戴尔", to: "洛丝萝林", depart: "08:00", arrive: "15:40", duration: "7h40m", seat: "叶舟 03 · 银树观景位", note: "入夜前抵达金色森林，未经允许不要偏离发光步道。" },
  { kind: "远征骑行令", service: "Riddermark Route · 洛汗远征线", from: "洛丝萝林", to: "洛汗 / 末日火山", depart: "06:20", arrive: "日落前", duration: "未知", seat: "栗色战马 · 左侧马镫", note: "穿过草原后补给，最后一段路将由意志而非地图导航。" },
];

const stops: Stop[] = [
  { id: "hobbiton", name: "霍比屯", companion: "霍比特旅人", image: "/middle-earth-checkins/hobbiton.webp", time: "07:30", route: "从袋底洞沿花园小径下坡，经过石桥与水磨坊。", activity: "在圆门、花田与宴会树之间，拍下远征真正开始前的宁静。", stamp: "SHIRE DEPARTURE", x: "13%", y: "76%" },
  { id: "rivendell", name: "瑞文戴尔", companion: "灰袍巫师", image: "/middle-earth-checkins/rivendell.webp", time: "16:45", route: "沿响水河进入幽谷，在瀑布旁的精灵露台停留。", activity: "和灰袍巫师一起眺望雪山，让这座避风港替旅程恢复勇气。", stamp: "ELVEN HAVEN", x: "32%", y: "51%" },
  { id: "lothlorien", name: "洛丝萝林", companion: "精灵弓手", image: "/middle-earth-checkins/lothlorien.webp", time: "20:10", route: "跟随银树上的金色灯光进入森林高台，不要离开悬桥。", activity: "在会发光的森林城市里与精灵弓手留下月色中的到此一游。", stamp: "GOLDEN WOOD", x: "51%", y: "27%" },
  { id: "rohan", name: "洛汗平原", companion: "北境游侠", image: "/middle-earth-checkins/rohan.webp", time: "17:20", route: "穿出森林后一路向南，沿骑士扬起的尘线前往山丘堡垒。", activity: "站在风吹草低的高坡，与北境游侠一起确认下一段远征方向。", stamp: "RIDERS' MARK", x: "70%", y: "49%" },
  { id: "mount-doom", name: "末日火山", companion: "忠诚园丁", image: "/middle-earth-checkins/mount-doom.webp", time: "18:55", route: "离开补给营地后沿黑色山脊前进，只走被余晖照亮的安全路线。", activity: "把漫长旅程的最后一步交给忠诚与勇气，留下抵达终点的背影。", stamp: "QUEST COMPLETE", x: "87%", y: "17%" },
];

function parse(): Result | null {
  const raw = new URLSearchParams(window.location.search).get("result");
  if (!raw) return null;
  try { const p = decodeSharedResult(raw); const persona = getPersona(p.p); const answerPath = p.a ?? ""; return { persona, scores: p.s, answerPath, resultHash: createResultHash(persona.id, p.s, answerPath) }; } catch { return null; }
}

export function MiddleEarthExperience() {
  const [result, setResult] = useState<Result | null | undefined>();
  const [stage, setStage] = useState<Stage>("world");
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const [status, setStatus] = useState("");
  const orderRef = useRef<HTMLDivElement | null>(null);
  const mapRef = useRef<HTMLDivElement | null>(null);
  const selected = stops.find((stop) => stop.id === selectedId);

  useEffect(() => { setResult(parse()); const q = new URLSearchParams(window.location.search); const s = q.get("stage"); const restored: Stage = s === "order" || s === "map" || s === "checkin" ? s : "world"; const spot = q.get("spot"); setStage(restored); setSelectedId(restored === "checkin" && spot && stops.some((x) => x.id === spot) ? spot : null); }, []);
  function encoded() { return result ? encodeSharedResult({ p: result.persona.id, s: result.scores, a: result.answerPath }) : ""; }
  function urlFor(next: Stage | "result", spot?: string | null) { const url = new URL(window.location.href); url.pathname = next === "result" ? pathFor("/") : pathFor("/middle-earth/"); url.search = ""; url.searchParams.set("result", encoded()); if (next === "result") { url.searchParams.set("focus", "reality"); url.hash = "reality"; } else { url.searchParams.set("stage", next); if (next === "checkin" && spot) url.searchParams.set("spot", spot); url.hash = `middle-earth-${next}`; } return url.toString(); }
  function update(next: Stage, spot?: string) { setStage(next); if (next === "checkin") { setSelectedId(spot ?? null); setStatus(""); } window.history.pushState({}, "", urlFor(next, spot)); requestAnimationFrame(() => { if (next === "order") orderRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); if (next === "map" || next === "checkin") mapRef.current?.scrollIntoView({ behavior: "smooth", block: "start" }); }); }
  async function blob(stop: Stop) { const response = await fetch(pathFor(stop.image)); if (!response.ok) throw new Error(); return response.blob(); }
  function filename(stop: Stop) { return `middle-earth-${stop.id}-${result?.persona.code ?? "traveler"}.webp`; }
  function download(data: Blob, name: string) { const url = URL.createObjectURL(data); const a = document.createElement("a"); a.href = url; a.download = name; a.click(); setTimeout(() => URL.revokeObjectURL(url), 0); }
  async function save(stop: Stop) { setStatus("正在保存打卡图片…"); try { const data = await blob(stop); download(data, filename(stop)); setStatus(`${stop.name}打卡图片已保存`); } catch { setStatus("图片保存失败，请稍后重试"); } }

  if (result === undefined) return <main className="min-h-screen bg-[#132519]" />;
  if (result === null) return <main className="grid min-h-screen place-items-center bg-[#132519] p-6 text-white"><div className="rounded-[2rem] border border-white/20 bg-white/10 p-8 text-center"><h1 className="display text-4xl">中土入口失效</h1><p className="mt-4 font-bold text-white/70">请先完成旅行人格测试，再领取远征订单。</p><a href={pathFor("/")} className="mt-6 inline-flex rounded-xl bg-[#d9f99d] px-5 py-3 font-black text-[#17142f]">回到首页</a></div></main>;

  return <main className="min-h-screen bg-[#132519] pb-20 text-white"><div className="noise" />
    <header className="mx-auto flex max-w-6xl items-center justify-between px-5 py-6 sm:px-8"><button onClick={() => location.assign(urlFor("result"))} className="focus-ring rounded-full border border-white/20 bg-white/10 px-4 py-2 text-sm font-black">← 返回现实世界</button><span className="rounded-full border border-[#d9f99d]/40 bg-[#d9f99d]/10 px-3 py-1.5 text-xs font-black text-[#d9f99d]">{result.persona.code} · 远征许可已签发</span></header>
    <section data-testid="middle-earth-world" className="mx-auto max-w-6xl overflow-hidden rounded-[2rem] border-2 border-white/15 shadow-[0_18px_60px_rgba(0,0,0,.45)]">
      <div className="relative min-h-[44rem] overflow-hidden"><img src={pathFor("/middle-earth-hero.webp")} alt="远征队背对镜头眺望中土世界" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(9,25,15,.95),rgba(9,25,15,.63)_48%,transparent_82%),linear-gradient(0deg,rgba(9,25,15,.95),transparent_48%)]" /><div className="relative z-10 flex min-h-[44rem] flex-col justify-between p-6 sm:p-10 lg:p-12"><div className="flex flex-wrap gap-3"><span className="rounded-full border border-[#d9f99d]/45 bg-[#132519]/65 px-4 py-2 text-xs font-black uppercase tracking-[.18em] text-[#d9f99d]"><Sparkles className="mr-2 inline" size={15} />Middle-earth passage granted</span><span className="rounded-full border border-white/20 bg-white/10 px-4 py-2 text-xs font-black">远征队已集结 · 地图已展开</span></div><motion.div initial={{ opacity: 0, y: 24 }} animate={{ opacity: 1, y: 0 }} className="max-w-3xl"><p className="text-sm font-black tracking-[.18em] text-[#facc6b]">真正的远方，总从门外第一步开始</p><h1 className="display mt-3 text-6xl leading-[.9] sm:text-8xl lg:text-9xl">Middle-earth<br /><span className="text-[#d9f99d]">中土世界</span></h1><p className="mt-6 max-w-2xl text-lg font-bold leading-relaxed text-white/85 sm:text-xl">从夏尔的早餐出发，经过精灵幽谷、金色森林与洛汗草原，最终走到火山前。属于 <span className="text-[#d9f99d]">{result.persona.code}</span> 的史诗远征已经写好开篇。</p><div className="mt-7 grid max-w-2xl gap-3 text-sm font-black sm:grid-cols-3"><div className="rounded-2xl border border-white/20 bg-[#132519]/65 p-4"><MapPin className="mb-2 text-[#d9f99d]" size={18} />起点：霍比屯</div><div className="rounded-2xl border border-white/20 bg-[#132519]/65 p-4"><Footprints className="mb-2 text-[#d9f99d]" size={18} />五段史诗远征</div><div className="rounded-2xl border border-white/20 bg-[#132519]/65 p-4"><Camera className="mb-2 text-[#d9f99d]" size={18} />五张旅伴背影照</div></div><button onClick={() => update("order")} className="button-pop focus-ring mt-8 inline-flex items-center gap-2 rounded-2xl border-2 border-[#17142f] bg-[#d9f99d] px-6 py-4 text-lg font-black text-[#17142f] shadow-[5px_5px_0_white]"><TentTree size={21} /> 领取中土远征订单</button></motion.div></div></div>
      {(stage === "order" || stage === "map" || stage === "checkin") && <motion.div ref={orderRef} data-testid="middle-earth-order" initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} className="scroll-mt-4 bg-[#fffdf7] p-6 text-[#17142f] sm:p-10"><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-xs font-black uppercase tracking-[.2em] text-[#4d7c0f]">Quest order · 远征订单</p><h2 className="display mt-2 text-4xl sm:text-5xl">中土世界远征订单已生成</h2><p className="mt-3 font-bold text-black/60">订单 ME-{result.resultHash.replace("#TPI-", "")} · 路程可能因鹰、巫师或命运临时改道。</p></div><button onClick={() => update("map")} className="group button-pop focus-ring rounded-xl border-2 border-[#17142f] bg-[#facc6b] px-5 py-3 font-black shadow-[4px_4px_0_#17142f]"><span className="group-hover:hidden"><ScrollText className="mr-2 inline" size={18} />3 张凭证待验</span><span className="hidden group-hover:inline"><BadgeCheck className="mr-2 inline" size={18} />打开远征攻略</span></button></div>
        <div className="mt-8 grid gap-4 lg:grid-cols-3">{passes.map((pass, index) => <article key={pass.kind} className="flex min-h-[20rem] flex-col rounded-2xl border-2 border-[#17142f] bg-white p-5 shadow-[5px_5px_0_#84a95c]"><div className="border-b-2 border-dashed border-black/20 pb-4"><span className="text-xs font-black text-black/45">PASS 0{index + 1}</span><h3 className="display mt-1 text-3xl">{pass.kind}</h3></div><p className="mt-4 text-sm font-black text-[#4d7c0f]">{pass.service}</p><div className="mt-5 grid gap-3"><p><span className="text-xs font-black text-black/40">FROM</span><br /><b>{pass.from}</b></p><p><span className="text-xs font-black text-black/40">TO</span><br /><b>{pass.to}</b></p></div><div className="mt-4 grid grid-cols-3 rounded-xl bg-[#f1f7e9] p-3 text-center text-sm"><b>{pass.depart}</b><b>{pass.arrive}</b><b>{pass.duration}</b></div><p className="mt-4 text-sm font-bold text-black/65">{pass.seat}</p><p className="mt-auto pt-4 text-sm font-bold text-black/55">{pass.note}</p></article>)}</div>
        {(stage === "map" || stage === "checkin") && <motion.div ref={mapRef} data-testid="middle-earth-map" className="mt-10 rounded-[2rem] border-2 border-[#17142f] bg-[#132519] p-5 text-white shadow-[7px_7px_0_#17142f] sm:p-7"><div className="flex flex-col justify-between gap-4 xl:flex-row xl:items-end"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[.2em] text-[#d9f99d]">Quest guide · 远征攻略</p><h2 className="display mt-2 whitespace-nowrap text-lg sm:text-3xl lg:text-4xl xl:text-[2.5rem]">凭证确认，远征从绿门外开始</h2><p className="mt-3 font-bold text-white/70">点击地点查看契合该区域的旅伴背影打卡图。</p></div><div className="w-full overflow-x-auto whitespace-nowrap rounded-xl bg-white/10 px-4 py-3 text-[11px] font-black sm:text-sm xl:w-auto xl:min-w-[30rem] xl:text-center">霍比屯 → 瑞文戴尔 → 洛丝萝林 → 洛汗 → 末日火山</div></div>
          <div className="mt-7 grid items-start gap-5 lg:grid-cols-[.82fr_1.18fr]"><div className="space-y-5"><div className="relative aspect-square min-h-[26rem] overflow-hidden rounded-2xl border-2 border-white/15"><img src={pathFor("/world-maps/middle-earth.webp")} alt="中土世界五站远征路线地图" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-black/10" />{stops.map((stop, i) => <button key={stop.id} onClick={() => update("checkin", stop.id)} style={{ left: stop.x, top: stop.y }} className="button-pop focus-ring absolute z-10 flex -translate-x-1/2 -translate-y-1/2 flex-col items-center gap-2"><span className={`grid h-12 w-12 place-items-center rounded-full border-2 border-white font-black shadow-[3px_3px_0_rgba(0,0,0,.45)] ${selectedId === stop.id ? "bg-[#d9f99d] text-[#17142f]" : "bg-white text-[#17142f]"}`}>{i + 1}</span><span className="rounded-full bg-[#132519]/85 px-3 py-1 text-xs font-black">{stop.name}</span></button>)}</div>{selected && <div className="rounded-2xl border border-white/15 bg-white/10 p-5"><p className="text-xs font-black text-[#d9f99d]">{selected.time} · {selected.stamp}</p><h3 className="display mt-2 text-4xl">{selected.name}</h3><p className="mt-2 font-black text-[#facc6b]">本次同行：{selected.companion}</p><p className="mt-4 text-xl font-black">{selected.activity}</p><p className="mt-3 text-sm font-bold text-white/70">{selected.route}</p></div>}</div>
            <div className="rounded-2xl bg-[#fffdf7] p-4 text-[#17142f]">{selected ? <><motion.div key={selected.id} data-testid="middle-earth-checkin-image" className="overflow-hidden rounded-[1.5rem] border-2 border-[#17142f] shadow-[5px_5px_0_#84a95c]"><img src={pathFor(selected.image)} alt={`${selected.companion}在${selected.name}的背影打卡图`} className="block h-auto w-full object-contain" /></motion.div><div className="mt-4 grid grid-cols-[.78fr_1.22fr] gap-3"><button onClick={() => save(selected)} className="button-pop rounded-xl border-2 border-[#17142f] bg-[#facc6b] px-3 py-3 font-black"><Download className="mr-2 inline" size={18} />保存图片</button><button onClick={() => location.assign(urlFor("result"))} className="rounded-xl border-2 border-[#17142f] bg-[#d9f99d] px-4 py-3 font-black"><Compass className="mr-2 inline" size={18} />远征结束，返回现实</button></div>{status && <p role="status" className="mt-3 rounded-xl bg-[#17142f] p-3 text-center text-sm font-black text-white">{status}</p>}</> : <div className="grid min-h-[26rem] place-items-center text-center"><div><Camera className="mx-auto text-[#4d7c0f]" /><h3 className="display mt-4 text-3xl">选择第一个远征点</h3></div></div>}</div></div></motion.div>}
      </motion.div>}
    </section></main>;
}
